#!/bin/sh

. /lib/blue-merle/functions.sh


show_message() {
    # There is mcu_send_message() in /lib/functions/gl_util.sh but we don't want to load the file, thinking that it will take too long
    echo {\"msg\": \"$1\"} > /dev/ttyS0
}


logger -p notice -t blue-merle-libexec  "Libexec $1"

if [ "$1" == "read-imei" ]; then
    imei="$(READ_IMEI)"
    echo -n  $imei
    show_message "My IMEI: $imei"

elif [ "$1" == "read-imsi" ]; then
    imsi="$(READ_IMSI)"
    if [ "x$imsi" == "x" ]; then
        echo "No IMSI found $imsi" >&2
        exit 1
    else
        echo -n  $imsi
        show_message "My IMSI: $imsi"
    fi

elif [ "$1" == "random-imei" ]; then
    flock -n /tmp/blue-merle-imei-generate.lock  timeout 15  /lib/blue-merle/imei_generate.py --random
    READ_IMEI

elif [ "$1" == "shutdown-modem" ]; then
    exec gl_modem AT AT+CFUN=4

elif [ "$1" == "shutdown" ]; then
    show_message "Shutting down..."
    echo -n "Shutting down"
    logger -p notice -t blue-merle-libexec "Shutting down"
    echo '{ "poweroff": "1" }' > /dev/ttyS0

elif [ "$1" == "write-imei" ]; then
    new_imei=$2
    echo -n  { "action": "write" }

elif [ "$1" == "check-ttl" ]; then
    CHECK_TTL
    if [ $? -eq 0 ]; then
        show_message "TTL: Windows-like (128)"
        echo -n "TTL configured correctly for Windows emulation"
    else
        show_message "TTL: Linux-like (64)"
        echo -n "TTL needs adjustment for Windows emulation"
    fi

elif [ "$1" == "check-tcp" ]; then
    CHECK_TCP_WINDOWS
    if [ $? -eq 0 ]; then
        show_message "TCP: Windows-like configuration"
        echo -n "TCP stack configured for Windows emulation"
    else
        show_message "TCP: Needs adjustment"
        echo -n "TCP stack needs adjustment for Windows emulation"
    fi

elif [ "$1" == "check-dhcp" ]; then
    CHECK_DHCP_WINDOWS
    if [ $? -eq 0 ]; then
        show_message "DHCP: Windows-like client (dhcpcd)"
        echo -n "DHCP client configured for Windows emulation"
    else
        show_message "DHCP: Linux default (udhcpc)"
        echo -n "DHCP client needs upgrade to dhcpcd for Windows-like behavior"
    fi

elif [ "$1" == "check-dns" ]; then
    CHECK_DNS_SIMULATION
    if [ $? -eq 0 ]; then
        show_message "DNS: Windows background simulation active"
        echo -n "Windows DNS background simulation running securely"
    else
        show_message "DNS: Simulation inactive or insecure"
        echo -n "DNS simulation needs attention"
    fi

elif [ "$1" == "check-emulation" ]; then
    CHECK_WINDOWS_EMULATION
    if [ $? -eq 0 ]; then
        show_message "Windows emulation: EXCELLENT"
        echo -n "Windows 11 emulation configured excellently"
    else
        show_message "Windows emulation: NEEDS IMPROVEMENT"
        echo -n "Windows 11 emulation needs improvement"
    fi

elif [ "$1" == "check-risks" ]; then
    ANALYZE_DETECTION_RISKS
    if [ $? -eq 0 ]; then
        show_message "Risk analysis: LOW RISK"
        echo -n "Windows emulation detection risk analysis completed"
    else
        show_message "Risk analysis: NEEDS REVIEW"
        echo -n "Windows emulation needs review"
    fi

else
    echo -n   '{"msg":"Hello, World!"}'
    #echo 'foo'>&2
    echo 0
fi